[general]
dipper_contract = "0xdC627c1358c6480d51EF71B933633eE849ea92e1"

[sniping]
# Tokens to buy (no decimals wrapped) (applicable only for wallets using the "<config>" value under the wallet "tokens_amount" field)
tokens_amount="0.98%"

# Swap Threshold for triggering a contract sell
swap_threshold_tokens_amount="2000000000000000000000000"

# The maximum eth spent for dipping the contract
max_eth_spent_on_dipping=1.7

# Number of dipping rounds (swap buy / swap sell loops)
max_dipper_rounds=100

# The max number of user-swaps that are allowed to fail (specify 0 for none)
max_failed_user_swaps=0

# Minimum ETH Liquidity to consider as enableTrading = True
min_eth_liquidity=0

spammer_secs_delay=12

[tx_builder]
snipe_gas_limit="5139815"
max_fee_per_gas=10
max_priority_fee_per_gas=10

[provider]
rpc_url = "http://127.0.0.1:8545"