[general]
# The address of the Dipper contract to interact with
dipper_contract = "0x25cd69cf8d8fB35263A6D3e35a821288C6F48867"

[sniping]
# The amount of tokens to buy, specified as a percentage (e.g., "0.98%")
# Applicable only for wallets using the "<config>" value under the wallet's "tokens_amount" field
tokens_amount = "0.98%"

# The token amount threshold that triggers a contract sell
swap_threshold_tokens_amount = "4206900000000000000"

# The maximum amount of ETH to spend on dipping the contract
max_eth_spent_on_dipping = 4

# The maximum number of dipping rounds (swap buy/sell loops)
max_dipper_rounds = 100

# The maximum number of user swaps allowed to fail (specify 0 for none)
max_failed_user_swaps = 0

# The minimum ETH liquidity required to consider that trading is enabled (enableTrading = True)
min_eth_liquidity = 1

# The expected percentage variation in liquidity pool after dipping (e.g., 50.0 for 50%)
expected_lp_variation_after_dip = 20.0

# The delay in seconds between spammer txs
spammer_secs_delay = 12

[tx_builder]
dipper_gas_limit = "8139815"

# The gas limit for the snipe transaction
snipe_gas_limit = "1000000"

approve_gas_limit = "50000"

sell_gas_limit = "1000000"

sell_slippage_percent = 30.0

# The maximum fee per gas in Gwei
max_fee_per_gas = 10

# The maximum priority fee per gas in Gwei
max_priority_fee_per_gas = 10

# Whether to use a Gas Oracle for fetching gas prices
gas_oracle = true

[provider]
# The RPC URL of the Ethereum node provider
# rpc_url = "http://127.0.0.1:8545"
rpc_url = "https://mainnet.infura.io/v3/e4a9193a1f35493786c001c3573f7905"
